In [1]:
import pandas as pd
train=pd.read_csv(r'C:\Users\Dell\Downloads\train_doc.csv')
test=pd.read_csv(r'C:\Users\Dell\Downloads\test_doc.csv')
 
train.dropna(inplace=True)
test.dropna(inplace=True)

train

                                                   text  output
0     form rev september department treasury interna...       5
1     form w purpose complete form w employer withho...       5
2     invoice afeel corp dba huntington brass dana c...       2
3     format ion technology telecommunication admini...       3
4     heather burtch burtchhm gmail com ellicott cit...       4
...                                                 ...     ...
1001  company report generated parkeon transit limit...       6
1002  cxtec north american office south bay road nor...       2
1003  gifford drive aC spring hill fl aC aC mkile gm...       4
1004  blake w price hamptona hillsa blvd canton m pi...       4
1005  form w rev december department treasury intern...       5

[1003 rows x 2 columns]

In [2]:
train=train.head(5)
test=test.head(50)

In [2]:
import re
cList = {
  "ain't": "am not",
  "aren't": "are not",
  "can't": "cannot",
  "can't've": "cannot have",
  "'cause": "because",
  "could've": "could have",
  "couldn't": "could not",
  "couldn't've": "could not have",
  "didn't": "did not",
  "doesn't": "does not",
  "don't": "do not",
  "hadn't": "had not",
  "hadn't've": "had not have",
  "hasn't": "has not",
  "haven't": "have not",
  "he'd": "he would",
  "he'd've": "he would have",
  "he'll": "he will",
  "he'll've": "he will have",
  "he's": "he is",
  "how'd": "how did",
  "how'd'y": "how do you",
  "how'll": "how will",
  "how's": "how is",
  "I'd": "I would",
  "I'd've": "I would have",
  "I'll": "I will",
  "I'll've": "I will have",
  "I'm": "I am",
  "I've": "I have",
  "isn't": "is not",
  "it'd": "it had",
  "it'd've": "it would have",
  "it'll": "it will",
  "it'll've": "it will have",
  "it's": "it is",
  "let's": "let us",
  "ma'am": "madam",
  "mayn't": "may not",
  "might've": "might have",
  "mightn't": "might not",
  "mightn't've": "might not have",
  "must've": "must have",
  "mustn't": "must not",
  "mustn't've": "must not have",
  "needn't": "need not",
  "needn't've": "need not have",
  "o'clock": "of the clock",
  "oughtn't": "ought not",
  "oughtn't've": "ought not have",
  "You've":"You have",
  "shan't": "shall not",
  "sha'n't": "shall not",
  "shan't've": "shall not have",
  "she'd": "she would",
  "she'd've": "she would have",
  "she'll": "she will",
  "she'll've": "she will have",
  "she's": "she is",
  "should've": "should have",
  "shouldn't": "should not",
  "shouldn't've": "should not have",
  "so've": "so have",
  "so's": "so is",
  "that'd": "that would",
  "that'd've": "that would have",
  "that's": "that is",
  "there'd": "there had",
  "there'd've": "there would have",
  "there's": "there is",
  "they'd": "they would",
  "they'd've": "they would have",
  "they'll": "they will",
  "they'll've": "they will have",
  "they're": "they are",
  "they've": "they have",
  "to've": "to have",
  "wasn't": "was not",
  "we'd": "we had",
  "we'd've": "we would have",
  "we'll": "we will",
  "we'll've": "we will have",
  "we're": "we are",
  "we've": "we have",
  "weren't": "were not",
  "what'll": "what will",
  "what'll've": "what will have",
  "what're": "what are",
  "what's": "what is",
  "what've": "what have",
  "when's": "when is",
  "when've": "when have",
  "where'd": "where did",
  "where's": "where is",
  "where've": "where have",
  "who'll": "who will",
  "who'll've": "who will have",
  "who's": "who is",
  "who've": "who have",
  "why's": "why is",
  "why've": "why have",
  "will've": "will have",
  "won't": "will not",
  "won't've": "will not have",
  "would've": "would have",
  "wouldn't": "would not",
  "wouldn't've": "would not have",
  "y'all": "you all",
  "y'alls": "you alls",
  "y'all'd": "you all would",
  "y'all'd've": "you all would have",
  "y'all're": "you all are",
  "y'all've": "you all have",
  "you'd": "you had",
  "you'd've": "you would have",
  "you'll": "you you will",
  "you'll've": "you you will have",
  "you're": "you are",
  "you've": "you have"
}
c_re = re.compile('|'.join(cList.keys()))

In [3]:
from nltk.corpus.reader.wordnet import WordNetError
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import re
class NLTKPreprocessing():
    
    def __init__(self, text_input): 
        self.__text_input = text_input
        self.__result=None
        
#expanding contraction
      
    def expandContractions(self, parameter_dictionary):
        def replace(match):
            return cList[match.group()]#match.group() returns part of string where there is a match
        self.__result=c_re.sub(replace, self.__text_input)
        return self.__result
    
#replacing special character,numbers,email,unicode

    def replace_func(self,parameter_dictionary): 
        
        text=self.expandContractions({})
        reg_ex=[r'\\u[0-9a-fA-Z]{4}','[0-9]+','[a-z,0-9,A-Z]+@[a-z]+.com','[^a-zA-z0-9]','^\s*|\s\s*',r'(.+?)\1+',r'\b[a-zA-Z]\b']
        for i in reg_ex:
            text=re.sub(i, " ",text)
            self.__text_input=text
            
        self.__result=self.__text_input
        return self.__result 
        
        
#assigning tokens to words

    def tokenization(self,parameter_dictionary): 
        
        new_text=self.replace_func({})
        token_type=parameter_dictionary.get("token type","sent")
        
        if token_type=="word":
            #tokenizer.train(self.__text_input)
            res=word_tokenize(new_text)
        else:
            res=sent_tokenize(new_text)
        self.__result=res
        
        return self.__result

#removing stop words

    def removeStopwords(self,parameter_dictionary):

        try:
            stop_words=set(stopwords.words('english'))
            words=self.tokenization({"token type":"word"})
        
            filtered_words= [w for w in words if not w in stop_words]
            self.__result=filtered_words
        except AttributeError:
            print("")
        except WordNetError:
            print("")
        except:
            print("")
        return self.__result

In [4]:
LibraryBase={
    "nltk":NLTKPreprocessing
    }

In [5]:
class MainFunc():
    def __init__(self):
        self.__result=None
        
    
    def preprocessing_text(self,in_text,lib_name,function_name,par_dict):
        
        classname=LibraryBase.get(lib_name,"nltk")
        
        class_ref=classname(in_text)
        res=getattr(class_ref,function_name)(par_dict)
        self.__result=res
        return self.__result
    
    def main_start(self,input_text,class_name,method_name):
        
        param_dict={"token type":"word"}
        
        self.__result=self.preprocessing_text(input_text,class_name,method_name,param_dict)
        
        return self.__result

In [ ]:
from concurrent.futures import ThreadPoolExecutor
from csv import writer

train_tokenized_df=pd.DataFrame(columns=['tokenized_sent'])

m=MainFunc()
#wn.ensure_loaded()
count=0
def add_features(splited_frame):
    count=0
    train_tokenized=(m.main_start(splited_frame,'nltk','removeStopwords')).copy()
    print(count)
    #append_list_as_row(r'C:\Users\Dell\Downloads\train_tokenized.xlsx',train_tokenized)
    #with open(r'C:\Users\Dell\Downloads\train_tokenized_new.csv', 'a+', newline='') as write_obj:
        # Create a writer object from csv module
        #csv_writer = writer(write_obj)
        # Add contents of list as last row in the csv file
        #csv_writer.writerow(train_tokenized)
    count=count+1
    return train_tokenized


def parallelize_dataframe(train_text):
 
    with ThreadPoolExecutor(max_workers=10) as executor:
       
        train_tokenized=executor.map(add_features, train_text)
        return train_tokenized 
    

train_tokenized=parallelize_dataframe(train.text)
for result in train_tokenized:
    df_length = len(train_tokenized_df)
    train_tokenized_df.loc[df_length,'tokenized_sent'] = result

In [25]:
train_tokenized_df.to_csv(r'C:\Users\Dell\Downloads\train_tokenized_new.csv',columns=['tokenized_sent'],index=False)

In [20]:
result=pd.read_csv(r'C:\Users\Dell\Downloads\train_tokenized_new.csv')
result

,form,rev,september,department,treasury,internal,revenue,service,lication,voluntary,...,operation,icer,codeofbarcode,guidance.1,center.1,retirement.2,plan.92,pre,roved,plan.93
0,invoice,af,corp,dba,huntington,bra,dana,circle,cypre,ca,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,heather,hm,gmail,com,ico,city,md,experience,rainking,solution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,form,purpose,complete,form,employer,wit,old,co,ect,federal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,format,ion,technology,teleco,unication,administration,core,product,work,avaya,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,form,rev,september,department,treasury,internal,revenue,service,lication,voluntary,...,operation,icer,codeofbarcode,guidance,center,retirement,plan,pre,roved,plan
5,"['form', 'rev', 'september', 'department', 'tr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"['invoice', 'af', 'corp', 'dba', 'huntington',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"['heather', 'hm', 'gmail', 'com', 'ico', 'city...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"['format', 'ion', 'technology', 'teleco', 'uni...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"['form', 'purpose', 'complete', 'form', 'emplo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"['form', 'rev', 'september', 'department', 'tr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"['heather', 'hm', 'gmail', 'com', 'ico', 'city...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"['form', 'purpose', 'complete', 'form', 'emplo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,"['format', 'ion', 'technology', 'teleco', 'uni...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"['invoice', 'af', 'corp', 'dba', 'huntington',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,form,rev,september,department,treasury,internal,revenue,service,lication,voluntary,...,operation,icer,codeofbarcode,guidance,center,retirement,plan,pre,roved,plan
16,invoice,af,corp,dba,huntington,bra,dana,circle,cypre,ca,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,heather,hm,gmail,com,ico,city,md,experience,rainking,solution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,format,ion,technology,teleco,unication,administration,core,product,work,avaya,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,form,purpose,complete,form,employer,wit,old,co,ect,federal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
final_dict = {0: 'Bank Statements', 1: 'Insurance', 2: 'Invoice', 3: 'Manual',
              4: 'Resume', 5: 'Taxes', 6: 'mortgage', 7: 'pressrelease'}

In [ ]:
from sklearn.pipeline import Pipeline

pipe=pipeline([('cv',CountVectorizer()),
              ('tfidf',TfidfTransformer()),
              ('est',MultinomialNB()),])

parameters={tfidf__idf_:(True,False),
            est__alpha:(1e1,1e-3),
            est__fit_prior:(True,False)}

In [ ]:
from sklearn.model_selection import GridSearchCV
gs=GridSearchCV(pipe,parameters,n_jobs=-1)
gs_fit=gs.fit(train.text,train.output)

In [ ]:
predicted=gd_fit.predict(test.text)

In [ ]:
print(classification_report(train.output,predicted,labels=final_dict.values()))